#ifndef __DROPBEAR_CONFIG_H__
#define __DROPBEAR_CONFIG_H__ 1

#define BUNDLED_LIBTOM 1
#define CONF_UTMP_FILE "/var/run/utmp"
#define DISABLE_LASTLOG 1
#define DISABLE_PAM 1
#define DISABLE_SYSLOG 1
#define DISABLE_UTMP 1
#define DISABLE_UTMPX 1
#define DISABLE_WTMP 1
#define DISABLE_WTMPX 1
#define DROPBEAR_FUZZ 0
#define DROPBEAR_PLUGIN 0
#define HAVE_BASENAME 1
#define HAVE_CLEARENV 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CONST_GAI_STRERROR_PROTO 1
#define HAVE_DAEMON 1
#define HAVE_ENDUTENT 1
#define HAVE_FORK 1
#define HAVE_FREEADDRINFO 1
#define HAVE_GAI_STRERROR 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETGROUPLIST 1
#define HAVE_GETNAMEINFO 1
#define HAVE_GETUTENT 1
#define HAVE_INTTYPES_H 1
#define HAVE_LASTLOG_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_LIBZ 1
#define HAVE_LINUX_PKT_SCHED_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_IN_SYSTM_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_OPENPTY 
#define HAVE_PATHS_H 1
#define HAVE_PTY_H 1
#define HAVE_PUTENV 1
#define HAVE_PUTUTLINE 1
#define HAVE_SETUTENT 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRLCAT 1
#define HAVE_STRLCPY 1
#define HAVE_STRUCT_ADDRINFO 1
#define HAVE_STRUCT_IN6_ADDR 1
#define HAVE_STRUCT_SOCKADDR_IN6 1
#define HAVE_STRUCT_SOCKADDR_STORAGE 1
#define HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1
#define HAVE_STRUCT_UTMP_UT_ADDR 1
#define HAVE_STRUCT_UTMP_UT_ADDR_V6 1
#define HAVE_STRUCT_UTMP_UT_EXIT 1
#define HAVE_STRUCT_UTMP_UT_HOST 1
#define HAVE_STRUCT_UTMP_UT_ID 1
#define HAVE_STRUCT_UTMP_UT_PID 1
#define HAVE_STRUCT_UTMP_UT_TIME 1
#define HAVE_STRUCT_UTMP_UT_TV 1
#define HAVE_STRUCT_UTMP_UT_TYPE 1
#define HAVE_SYS_PRCTL_H 1
#define HAVE_SYS_RANDOM_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT8_T 1
#define HAVE_UNISTD_H 1
#define HAVE_UTMPNAME 1
#define HAVE_UTMP_H 1
#define HAVE_U_INT16_T 1
#define HAVE_U_INT32_T 1
#define HAVE_U_INT8_T 1
#define HAVE_WRITEV 1
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME ""
#define PACKAGE_STRING ""
#define PACKAGE_TARNAME ""
#define PACKAGE_URL ""
#define PACKAGE_VERSION ""
#define SELECT_TYPE_ARG1 int
#define SELECT_TYPE_ARG234 (fd_set *)
#define SELECT_TYPE_ARG5 (struct timeval *)
#define STDC_HEADERS 1
#ifndef _DARWIN_USE_64_BIT_INODE
# define _DARWIN_USE_64_BIT_INODE 1
#endif
#define _FILE_OFFSET_BITS 64
#define _GNU_SOURCE

#endif /* __DROPBEAR_CONFIG_H__ */
